set_property SRC_FILE_INFO {cfile:C:/eFPGA/OPDRACHT_2/EX_1_ROT_ENC/EX_1_ROT_ENC.srcs/constrs_1/new/XDC.xdc rfile:../../../EX_1_ROT_ENC.srcs/constrs_1/new/XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports RT1_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports RT2_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports {ROT_VAL_0[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {ROT_VAL_0[1]}]
