set_property SRC_FILE_INFO {cfile:C:/eFPGA/OPDRACHT_2/2/EX_2_MATRIX/EX_2_MATRIX.srcs/constrs_1/new/IP_MATRIX_XDC.xdc rfile:../../../EX_2_MATRIX.srcs/constrs_1/new/IP_MATRIX_XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports ST]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports SH]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports DS]
